# Generated by Django 3.2.9 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='app.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
